"""Initial migration

Revision ID: 392dcd7b8cb5
Revises: 2b0fcbeee229
Create Date: 2024-07-08 19:36:43.841029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392dcd7b8cb5'
down_revision = '2b0fcbeee229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
